### ISSUE TITLE
AWSSigV4 not thread safe

### ISSUE THREAD

**Issue by ims-swilkinson** [andrewjroth/requests-auth-aws-sigv4#12]
We were using a cached AWSSigV4 object which was shared between threads, and we'd very occasionally get a 403 error because the signature was wrong.
Looking at the code, it looks like it uses data members to store some timestamp related values when it's calculating the signing values:
https://github.com/andrewjroth/requests-auth-aws-sigv4/blob/c0fc37a3d6f60e5e0bf8fcffaa4ec06ee263eaab/requests_auth_aws_sigv4/__init__.py#L98

I know the workaround for us is easy: don't treat the AWSSigV4 as if it is thread safe. But as far as I can tell, it would be pretty easy to make it thread safe by using local variables instead of member variables. Have I missed something as to why member variables are used in this way?

**Comment by andrewjroth** [comment]
Looks good!  Thank you for your contribution!
