### ISSUE TITLE
Invalid token with temporary session token

### ISSUE THREAD

**Issue by shawnsparks-work** [andrewjroth/requests-auth-aws-sigv4#2]
This is working great for me when using basic access key id and secret access key values. However, if I'm using a temporary token, I get an error when calling AWS api due to an invalid token. I was able to confirm `requests-auth-aws-sigv4` is picking up the session token from my credentials file, but best guess is it isn't creating the signed header correctly?

**Comment by shawnsparks-work** [comment]
I switched over to use this package instead: https://github.com/davidmuller/aws-requests-auth

**Comment by andrewjroth** [comment]
This issue has been fixed in version 0.6, published to Pypi
