### ISSUE TITLE
Missing required header for requests with 'aws_session_token'

### ISSUE THREAD

**Issue by pghole** [andrewjroth/requests-auth-aws-sigv4#3]
How to reproduce ?

```
import requests
from requests_auth_aws_sigv4 import AWSSigV4

ACCESS_KEY = 'XXXXXXXX'
SECRET_KEY = 'XXXXXX'
SESSION_TOKEN = 'XXXXX'

aws_auth = AWSSigV4('s3',
    aws_access_key_id=ACCESS_KEY,
    aws_secret_access_key=SECRET_KEY,
    aws_session_token=SESSION_TOKEN,
    region= 'us-east-1',
)

r = requests.request('GET', 'https://<bucket_name>.s3.amazonaws.com/<location_on_s3>',
    auth=aws_auth)
print(r.text)

```
This gives following error message -

**Missing required header for this request: x-amz-content-sha256**

Pls.note this access_key, secret_key and session_token are valid and I have checked that using other packages.

**Comment by andrewjroth** [comment]
A fix has been added to the latest version published here and to Pypi

**Comment by andyfase** [comment]
Hi 

This issue still persists - at least for the S3 service. See https://docs.aws.amazon.com/AmazonS3/latest/API/bucket-policy-s3-sigv4-conditions.html

the header `x-amz-content-sha256` actually needs to be included in the payload of the request for S3. Adding something like this:

```
        if self.service == 's3':
            r.headers['x-amz-content-sha256'] = payload_hash
```

Allows S3 calls to work.

**Comment by andrewjroth** [comment]
This header is now added to every request and included in the signature.  Let me know if the issue persists.
