### ISSUE TITLE
AWSSigV4 should not overwrite existing headers such as Content-Type or User-Agent

### ISSUE THREAD

**Issue by danj** [andrewjroth/requests-auth-aws-sigv4#5]
The following request is modified by the AWSSigV4 which adds the signature but also changes the Content-Type header. 

```
requests.get(url, auth=AWSSigV4(service='execute-api'), headers={'Content-Type': 'application/json'})
```

Changing the Content-Type to "application/x-www-form-urlencoded; charset=utf-8" may cause the request to fail on the server side.

The [sigv4](https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html)  spec doesn't require signing the Content-Type header, so by simply removing this update to the headers dictionary I was able to work-around the issue. Alternatively, the header could be signed if it exists.

I don't think overwriting the User-Agent is a good idea either.

I'd be happy to submit a PR if you could provide some guidance on how you'd like to handle the existing headers

**Comment by tokicnikolaus** [comment]
I had same issues with request headers overwritten, you can check this lib [requests-aws4auth](https://pypi.org/project/requests-aws4auth/), worked for me :)

**Comment by andrewjroth** [comment]
Hello,

I fixed this by adding the headers only if they don't already exist.  The signature doesn't use these optional headers.  Please let me know if this fix works for you or continues to have issues.

Thanks!
