### ISSUE TITLE
Access token is missing in the request header

### ISSUE THREAD

**Issue by sunabako** [andrewjroth/requests-auth-aws-sigv4#7]
I am seeing the following issue and am not sure where I would add the `access_token` from reading your examples.
```
{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": "Access token is missing in the request header."
    }
  ]
}
```

**Comment by andrewjroth** [comment]
Hello.  I am guessing you are using this with Elasticsearch Service (now called OpenSearch)?

AWS does not use the term `access_token` in [their documentation on static credentials](https://docs.aws.amazon.com/sdkref/latest/guide/feature-static-credentials.html), so I believe this is the `aws_session_token`.  Please review the documentation and use the example provided below.

```python
import requests
from requests_auth_aws_sigv4 import AWSSigV4

es_host = 'search-service-foobar.us-east-1.es.amazonaws.com'

aws_auth = AWSSigV4('es',
    aws_access_key_id=ACCESS_KEY,
    aws_secret_access_key=SECRET_KEY,
    aws_session_token=SESSION_TOKEN,
)

r = requests.request('GET', f"https://{es_host}/",
    auth=aws_auth)
print(r.text)
```

If you still have problems, please provide sample code on how to recreate the error.

Thanks!
